<a href="https://colab.research.google.com/github/spannav/PythonDataViz2026/blob/main/HW6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ศุภณัฏฐ์ ปุณมา ID 673020627-7

HW (ให้ใช้เฉพาะที่อาจารย์สอนไปแล้วในวิชานี้)

1.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของข้อมูลทั้งหมด
2.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของผู้ป่วยในจังหวัดขอนแก่น

In [1]:
import pandas as pd

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
path = '/content/drive/MyDrive/P3 T1/Aj.Ton/DATA/confirmed-cases-since-120864.csv'

In [10]:
data = pd.read_csv(path)
data.head()

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,816990,12/8/2021,11/8/2021,ชาย,7.0,ปี,Thailand,เชียงราย,อื่นๆ,NaN,NaN
1,816991,12/8/2021,11/8/2021,ชาย,1.0,ปี,Thailand,เชียงราย,อื่นๆ,NaN,NaN
2,816992,12/8/2021,11/8/2021,ชาย,35.0,ปี,Thailand,เชียงราย,อื่นๆ,NaN,NaN
3,816993,12/8/2021,11/8/2021,หญิง,33.0,ปี,Thailand,เชียงราย,อื่นๆ,NaN,NaN
4,816994,12/8/2021,11/8/2021,หญิง,14.0,ปี,Thailand,เชียงราย,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,NaN,NaN

In [12]:
this_data = data[['sex','age','province_of_isolation']]
this_data

          sex   age province_of_isolation
0         ชาย   7.0              เชียงราย
1         ชาย   1.0              เชียงราย
2         ชาย  35.0              เชียงราย
3        หญิง  33.0              เชียงราย
4        หญิง  14.0              เชียงราย
...       ...   ...                   ...
1042163   ชาย  45.0         กรุงเทพมหานคร
1042164   ชาย  31.0         กรุงเทพมหานคร
1042165   ชาย  31.0         กรุงเทพมหานคร
1042166   ชาย  24.0         กรุงเทพมหานคร
1042167   ชาย  25.0             เชียงใหม่

[1042168 rows x 3 columns]

In [51]:
male = this_data[this_data['sex'] == 'ชาย' ]
male['age']

0           7.0
1           1.0
2          35.0
5          39.0
6          45.0
           ...
1042163    45.0
1042164    31.0
1042165    31.0
1042166    24.0
1042167    25.0
Name: age, Length: 478004, dtype: float64

In [50]:
female = this_data[this_data['sex'] == 'หญิง' ]
female[['sex','age']]

          sex   age
3        หญิง  33.0
4        หญิง  14.0
7        หญิง  32.0
8        หญิง   7.0
11       หญิง  56.0
...       ...   ...
1041965  หญิง  67.0
1041966  หญิง  53.0
1041975  หญิง   NaN
1041976  หญิง   NaN
1041977  หญิง   NaN

[516452 rows x 2 columns]

In [34]:
def avg_age(data):
    sum = 0
    N = 0
    for i in data['age']:
        if i > 0:
          sum += i #sum = sum+i
          N += 1
    return sum/N

In [36]:
print(f' อายุเฉลี่ยของเพศหญิงคือ {avg_age(female)}')
print(f' อายุเฉลี่ยของเพศชายคือ {avg_age(male)}')

 อายุเฉลี่ยของเพศหญิงคือ 36.111554883071086
 อายุเฉลี่ยของเพศชายคือ 34.21406518778788

--------------------------------------------------------------------------------------------

คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของผู้ป่วยในจังหวัดขอนแก่น

In [38]:
kkc = this_data[this_data['province_of_isolation']== 'ขอนแก่น']
kkc

          sex   age province_of_isolation
12085     ชาย   NaN               ขอนแก่น
12086    หญิง  54.0               ขอนแก่น
12087     ชาย  40.0               ขอนแก่น
12088    หญิง  31.0               ขอนแก่น
12089    หญิง  30.0               ขอนแก่น
...       ...   ...                   ...
1036989   ชาย  78.0               ขอนแก่น
1036990  หญิง  69.0               ขอนแก่น
1036991  หญิง   1.0               ขอนแก่น
1036992   ชาย  65.0               ขอนแก่น
1036993  หญิง   9.0               ขอนแก่น

[13107 rows x 3 columns]

In [46]:
kkc_female = this_data[(this_data['province_of_isolation']== 'ขอนแก่น') & (this_data['sex']=='หญิง')]
kkc_female['age']

12086      54.0
12088      31.0
12089      30.0
12093      33.0
12094      36.0
           ...
1036978    18.0
1036979    22.0
1036990    69.0
1036991     1.0
1036993     9.0
Name: age, Length: 6629, dtype: float64

In [47]:
kkc_male = this_data[(this_data['province_of_isolation']== 'ขอนแก่น') & (this_data['sex']=='ชาย')]
kkc_male['age']

12085       NaN
12087      40.0
12090      61.0
12091      43.0
12092      59.0
           ...
1036986    72.0
1036987    28.0
1036988    26.0
1036989    78.0
1036992    65.0
Name: age, Length: 6475, dtype: float64

In [49]:
print(f'อายุเฉลี่ยของผู้ป่วยเพศชายในจังหวัดขอนแก่นคือ {avg_age(kkc_male)}')
print(f'อายุเฉลี่ยของผู้ป่วยเพศหญิงในจังหวัดขอนแก่นคือ {avg_age(kkc_female)}')

อายุเฉลี่ยของผู้ป่วยเพศชายในจังหวัดขอนแก่นคือ 32.860373181530676
อายุเฉลี่ยของผู้ป่วยเพศหญิงในจังหวัดขอนแก่นคือ 34.65988060615337

-------------------------------------------

3. หาจำนวนผู้ป่วยที่เป็นคน "**คนต่างชาติเดินทางมาจากต่างประเทศ**"

In [56]:
foreigner = data[data['nationality'] != 'Thailand']
len(foreigner)

172653